name: nextjs Docker Build & Publish
run-name: ${{ github.actor }} is learning GitHub Actions

# 이벤트 
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache nextjs build
        uses: actions/cache@v3
        id: pakage-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: print nextjs cache directory
        continue-on-error: true
        run:
          ls -la ${{ github.workspace }}/.next/cache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}    

      #도커 허브 배포
      - name: Build and push
        env: 
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO: ${{ secrets.GIT_REPO }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $NAME/$REPO:latest
          cache-from: type=registry,ref=$NAME/$REPO:latest
          cache-to: type=inline
      

      