name: nextjs Docker Build & Publish
run-name: ${{ github.actor }} is learning GitHub Actions

# 이벤트 
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}    
      - name: Build docker image and push to ECR
        uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          file: Dockerfile
          push: true
          tags: #ecr 주소
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #도커 허브 배포
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO: ${{ secrets.GIT_REPO }}
        with:
          context: .
          push: true
          tags: $NAME/$REPO:latest
          cache-from: type=registry,ref=$NAME/$REPO:buildcache
          cache-to: type=registry,ref=$NAME/$REPO:buildcache,mode=max
      

      